retake on ci.yml to work correctly

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,3 +1,5 @@
+name: API_CI
+run-name: ${{ github.actor }} My SpringBoot API CI
 on:
   push:
     branches: [master]
@@ -5,7 +7,7 @@ on:
       - 'src/**'
       - '.github/workflows/ci.yml'
   pull_request:
-    branches: [main]
+    branches: [master]
     paths:
       - 'src/**'
       - '.github/workflows/maven.yml'
@@ -25,21 +27,11 @@ jobs:
     runs-on: ubuntu-latest
     needs:
       - init-workflow
-    services:
-      mysql:
-        image: mysql:8.0
-        env:
-          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
-          MYSQL_DATABASE: springboot
-          MYSQL_USER: ${{ secrets.DB_USER }}
-          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
-        ports:
-          - 3306:3306
-        options: >-
-          --health-cmd="mysqladmin ping -h 127.0.0.1 --silent"
-          --health-interval=10s
-          --health-timeout=5s
-          --health-retries=3
+
+    env:
+
+      DB_USER: ${{ secrets.DB_USER }}
+      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
 
     steps:
       - name: Checkout code
@@ -47,32 +39,57 @@ jobs:
         with:
           fetch-depth: 0
 
-      - name: Wait for MySQL to be ready
-        run: |
-          for i in {30..0}; do
-            if mysqladmin ping -h 127.0.0.1 --silent; then
-              echo "MySQL is up!"
-              break
-            fi
-            echo 'Waiting for MySQL...'
-            sleep 2
-          done
+#   Create a Docker Service of MYSQL instead of starting directly on the system
 
-      - name: Debug MySQL Connection
-        run: |
-          mysqladmin ping -h 127.0.0.1 -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }}
-
-      - name: Check if SQL script exists
-        run: |
-          if [ ! -f mysql/script/db_springboot_api.sql ]; then
-          echo "❌ SQL script not found!"
-          exit 1
-          else
-            echo "✅ SQL script found!"
-          fi
+#    services:
+#      mysql:
+#        image: mysql:8.0
+#        env:
+#          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
+#          MYSQL_DATABASE: springboot
+#          MYSQL_USER: ${{ secrets.DB_USER }}
+#          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
+#        ports:
+#          - 3306:3306
+#        options: >-
+#          --health-cmd="mysqladmin ping -h 127.0.0.1 --silent"
+#          --health-interval=10s
+#          --health-timeout=5s
+#          --health-retries=3
+#
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v4
+#        with:
+#          fetch-depth: 0
+#
+#      - name: Wait for MySQL to be ready
+#        run: |
+#          for i in {30..0}; do
+#            if mysqladmin ping -h 127.0.0.1 --silent; then
+#              echo "MySQL is up!"
+#              break
+#            fi
+#            echo 'Waiting for MySQL...'
+#            sleep 2
+#          done
+#
+#      - name: Debug MySQL Connection
+#        run: |
+#          mysqladmin ping -h 127.0.0.1 -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }}
+#
+#      - name: Check if SQL script exists
+#        run: |
+#          if [ ! -f mysql/script/db_springboot_api.sql ]; then
+#          echo "❌ SQL script not found!"
+#          exit 1
+#          else
+#            echo "✅ SQL script found!"
+#          fi
+#
 
       - name: Create Database from script
-        run: mysql -h 127.0.0.1 -P 3306 -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} springboot < mysql/script/db_springboot_api.sql
+        run: mysql -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} -e "source mysql/script/db_springboot_api.sql"
 
       - name: Install Chrome for selenium
         uses: browser-actions/setup-chrome@latest
