update ci.yml test workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -58,8 +58,17 @@ jobs:
             sleep 2
           done
 
+      - name: Check if SQL script exists
+        run: |
+          if [ ! -f DemoSpringBoot_WenApp/mysql/script/db_springboot_api.sql ]; then
+          echo "❌ SQL script not found!"
+          exit 1
+          else
+            echo "✅ SQL script found!"
+          fi
+
       - name: Create Database from script
-        run: mysql -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} -e "source mysql/script/db_springboot_api.sql"
+        run: mysql -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} springboot < DemoSpringBoot_API/mysql/script/db_springboot_api.sql
 
       - name: Install Chrome for selenium
         uses: browser-actions/setup-chrome@latest
